version: "3.4"

services:
  portainer:
    command: "-H unix:///var/run/docker.sock"
    image: 'portainer/portainer'
    ports:
      - 9000:9000
    volumes:
      - /data/portainer:/data/portainer
      - /var/run/docker.sock:/var/run/docker.sock

    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.labels.portainer == 1
      restart_policy:
        condition: on-failure
